<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="69791" started-at="2015-12-22T20:46:07Z" finished-at="2015-12-22T20:47:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="69791" started-at="2015-12-22T20:46:07Z" finished-at="2015-12-22T20:47:17Z">
      <class name="com.globant.tests.Tests">
        <test-method status="PASS" signature="before()[pri:0, instance:com.globant.tests.Tests@2133c8f8]" name="before" is-config="true" duration-ms="2692" started-at="2015-12-22T17:46:07Z" finished-at="2015-12-22T17:46:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="FAIL" signature="testSearchFlightAndNavigateToTripInformation()[pri:0, instance:com.globant.tests.Tests@2133c8f8]" name="testSearchFlightAndNavigateToTripInformation" duration-ms="66691" started-at="2015-12-22T17:46:10Z" finished-at="2015-12-22T17:47:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The data is not ordered correcly expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The data is not ordered correcly expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.globant.tests.Tests.verifyOrderTimeAsc(Tests.java:345)
	at com.globant.tests.Tests.testSearchFlightAndNavigateToTripInformation(Tests.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSearchFlightAndNavigateToTripInformation -->
        <test-method status="PASS" signature="after()[pri:0, instance:com.globant.tests.Tests@2133c8f8]" name="after" is-config="true" duration-ms="399" started-at="2015-12-22T17:47:17Z" finished-at="2015-12-22T17:47:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after -->
      </class> <!-- com.globant.tests.Tests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
